"""
Export Tool — Package dataset + generate Kaggle notebook untuk training YOLO.

Usage:
  python tools/export_kaggle.py                    # Lihat info & generate notebook
  python tools/export_kaggle.py --zip              # Buat zip + notebook
  python tools/export_kaggle.py --notebook-only    # Hanya generate notebook
"""

import argparse
import os
import shutil
import sys
import zipfile
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
DATASET_DIR = PROJECT / "trainings" / "hero_detector"


def dataset_info() -> dict:
    """Return dataset summary."""
    from collections import Counter

    lbl_dir = DATASET_DIR / "labels" / "train"
    img_dir = DATASET_DIR / "images" / "train"
    val_img = DATASET_DIR / "images" / "val"

    labels = list(lbl_dir.glob("*.txt"))
    c = Counter()
    for f in labels:
        for line in f.read_text().strip().split("\n"):
            parts = line.strip().split()
            if parts:
                c[int(parts[0])] += 1

    return {
        "train_imgs": len(list(img_dir.glob("*.png"))),
        "train_lbls": len(labels),
        "val_imgs": len(list(val_img.glob("*.png"))),
        "annotations": sum(c.values()),
        "classes": dict(sorted(c.items())),
    }


def generate_notebook(path: Path):
    """Generate Kaggle notebook .ipynb."""
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# MLBB Minimap — YOLOv11 Training\n",
                    "Auto-generated by MLBB Auto Pipeline\n",
                    "\n",
                    "## Dataset: hero_detector (11 classes)\n",
                ],
            },
            {
                "cell_type": "code",
                "metadata": {},
                "source": [
                    "# ── 1. Install dependencies ──\n",
                    "!pip install -q ultralytics\n",
                    "import ultralytics\n",
                    "print(f'Ultralytics {ultralytics.__version__}')\n",
                ],
            },
            {
                "cell_type": "code",
                "metadata": {},
                "source": [
                    "# ── 2. Find dataset path ──\n",
                    "import os, shutil\n",
                    "from pathlib import Path\n",
                    "from ultralytics import YOLO\n",
                    "\n",
                    "# Cari dataset — bisa dari Add Data (input) atau upload manual\n",
                    "POSSIBLE_PATHS = [\n",
                    "    Path('/kaggle/input/hero-detector'),\n",
                    "    Path('/kaggle/input/hero-detector-v2'),\n",
                    "    Path('/kaggle/input/hero_detector'),\n",
                    "    Path('/kaggle/working'),\n",
                    "    Path('/kaggle/working/hero_detector'),\n",
                    "    Path('/kaggle/input/datasets/bachtiarpanjaitan/hero-detector'),\n",
                    "]\n",
                    "\n",
                    "DATA_DIR = None\n",
                    "for p in POSSIBLE_PATHS:\n",
                    "    if p.exists() and (p / 'images' / 'train').exists():\n",
                    "        DATA_DIR = p\n",
                    "        break\n",
                    "\n",
                    "if DATA_DIR is None:\n",
                    "    # Extract from zip (upload manual)\n",
                    "    import zipfile\n",
                    "    for zpath in ['../input/hero_detector.zip', 'hero_detector.zip']:\n",
                    "        if os.path.exists(zpath):\n",
                    "            with zipfile.ZipFile(zpath) as z:\n",
                    "                z.extractall('/kaggle/working/')\n",
                    "            DATA_DIR = Path('/kaggle/working/hero_detector')\n",
                    "            break\n",
                    "\n",
                    "if DATA_DIR is None:\n",
                    "    raise FileNotFoundError('Dataset tidak ditemukan. Upload hero_detector.zip via Add Data.')\n",
                    "\n",
                    "print(f'✅ Dataset: {DATA_DIR}')\n",
                    "print(f'   Train: {len(list(DATA_DIR.glob(\"images/train/*.png\")))} images')\n",
                    "print(f'   Val:   {len(list(DATA_DIR.glob(\"images/val/*.png\")))} images')\n",
                ],
            },
            {
                "cell_type": "code",
                "metadata": {},
                "source": [
                    "# ── 3. Update data.yaml path ──\n",
                    "import yaml\n",
                    "\n",
                    "yaml_path = str(Path(DATA_DIR) / 'data.yaml')\n",
                    "with open(yaml_path) as f:\n",
                    "    cfg = yaml.safe_load(f)\n",
                    "\n",
                    "cfg['path'] = str(DATA_DIR)\n",
                    "cfg['train'] = 'images/train'\n",
                    "cfg['val'] = 'images/val'\n",
                    "\n",
                    "with open(yaml_path, 'w') as f:\n",
                    "    yaml.dump(cfg, f, default_flow_style=False)\n",
                    "\n",
                    "print('✅ data.yaml updated')\n",
                ],
            },
            {
                "cell_type": "code",
                "metadata": {},
                "source": [
                    "# ── 4. Training ──\n",
                    "model = YOLO('yolo11n.pt')\n",
                    "\n",
                    "results = model.train(\n",
                    "    data=str(yaml_path),\n",
                    "    epochs=30,\n",
                    "    imgsz=352,\n",
                    "    batch=16,\n",
                    "    lr0=0.005,\n",
                    "    lrf=0.01,\n",
                    "    hsv_h=0.0,       # No hue shift for blue/red heroes\n",
                    "    hsv_s=0.1,\n",
                    "    hsv_v=0.1,\n",
                    "    mosaic=0.0,       # Disable mosaic for small objects\n",
                    "    patience=25,\n",
                    "    device='cuda',\n",
                    "    project='hero_detector',\n",
                    "    name='yolo11n_minimap',\n",
                    "    exist_ok=True,\n",
                    "    workers=2,\n",
                    "    amp=True,\n",
                    ")\n",
                ],
            },
            {
                "cell_type": "code",
                "metadata": {},
                "source": [
                    "# ── 5. Export ONNX & download ──\n",
                    "model.export(format='onnx', imgsz=352)\n",
                    "\n",
                    "# Copy ke working dir\n",
                    "best_pt = Path('hero_detector/yolo11n_minimap/weights/best.pt')\n",
                    "best_onnx = Path('hero_detector/yolo11n_minimap/weights/best.onnx')\n",
                    "\n",
                    "if best_pt.exists():\n",
                    "    shutil.copy(best_pt, '/kaggle/working/best.pt')\n",
                    "    print(f'✅ best.pt: {best_pt.stat().st_size/1024/1024:.1f} MB')\n",
                    "if best_onnx.exists():\n",
                    "    shutil.copy(best_onnx, '/kaggle/working/best.onnx')\n",
                    "    print(f'✅ best.onnx: {best_onnx.stat().st_size/1024/1024:.1f} MB')\n",
                ],
            },
        ],
        "metadata": {
            "kaggle": {
                "accelerator": "GPU",
                "language": "python3",
                "kernelType": "notebook",
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    import json
    path.write_text(json.dumps(notebook, indent=1))
    print(f"  ✅ Notebook: {path}")


def create_zip(path: Path):
    """Zip dataset for Kaggle upload."""
    zip_path = path / "hero_detector.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for folder in ["images", "labels"]:
            for split in ["train", "val"]:
                dir_path = DATASET_DIR / folder / split
                if not dir_path.exists():
                    continue
                for f in sorted(dir_path.iterdir()):
                    z.write(f, f"{folder}/{split}/{f.name}")
        # data.yaml
        data_yaml = DATASET_DIR / "data.yaml"
        if data_yaml.exists():
            z.write(data_yaml, "data.yaml")

    size_mb = zip_path.stat().st_size / (1024 * 1024)
    print(f"  ✅ Dataset zip: {zip_path} ({size_mb:.1f} MB)")
    return zip_path


def main():
    ap = argparse.ArgumentParser(description="Export dataset + notebook untuk Kaggle")
    ap.add_argument("--zip", action="store_true", help="Buat zip dataset + notebook")
    ap.add_argument("--notebook-only", action="store_true", help="Hanya generate notebook")
    ap.add_argument("--output", "-o", type=str, default=str(PROJECT / ".tmp"),
                    help="Output directory (default: .tmp/)")
    args = ap.parse_args()

    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)

    # ── Info ──
    info = dataset_info()
    print("=" * 50)
    print("📊 Kaggle Export — Dataset Info")
    print("=" * 50)
    print(f"  Train images: {info['train_imgs']}")
    print(f"  Train labels: {info['train_lbls']}")
    print(f"  Val images:   {info['val_imgs']}")
    print(f"  Annotations:  {info['annotations']}")
    print(f"  Classes:      10 (hero, lord, thunder_fenrir, ...)")
    print()

    # ── Generate notebook ──
    nb_path = out_dir / "kaggle_training.ipynb"
    generate_notebook(nb_path)

    # ── Zip ──
    if args.zip:
        create_zip(out_dir)
    elif not args.notebook_only:
        print(f"\n  Jalankan dengan --zip untuk buat dataset + notebook")
        print(f"  Upload notebook ke Kaggle: {nb_path}")
        print()

    if args.zip:
        print(f"\n  📤 Upload ke Kaggle:")
        print(f"     1. https://www.kaggle.com/ → New Notebook")
        print(f"     2. Upload dataset: Add Data → Upload → {out_dir/'hero_detector.zip'}")
        print(f"     3. Upload notebook: File → Import → {nb_path}")
        print(f"     4. Run all cells (Accelerator: GPU)")
        print()


if __name__ == "__main__":
    main()
